### ISSUE TITLE
misaligned nodes from different source node

### ISSUE THREAD

**Issue by davidcl** [zxch3n/tidy#1]
Thanks for your lib, it might be useful for me. I noted a mis-alignement issue on your blog post, in the screenshot below the nodes are correctly aligned when sharing the same parent node (green line) whereas with different parents they are not (red line).

![image](https://user-images.githubusercontent.com/731370/174035041-74bf2f89-18b1-4f79-9743-dd881e99e856.png)

**Comment by zxch3n** [comment]
You can play with the [interactive example here](https://www.zxch3n.com/tidy/tidy/#interactive-example) to see whether the layered mode meets your need
