### ISSUE TITLE
How to use or extend for real mindmaps?

### ISSUE THREAD

**Issue by cloudspeech** [zxch3n/tidy#12]
I am really impressed by the performance and thoroughness of your library!

However, all examples presented grow the tree strictly downwards from a root node at the top.

You are motivating this library by reference to mindmap layout.

Real mindmaps have the root node at the center of a 2-d sheet, and layout needs to distribute branches in all directions to fill the 2-d sheet in an aesthetically pleasing way.

Can the library be configured for this use case? If not, how would one go about extending it in this fashion?

**Comment by zxch3n** [comment]
This kind of mind map is not supported directly. But one can make it work by splitting the children of the root into two groups and applying the algorithm twice. The layout of the first group goes from root to right, and the second one goes from root to left.

<img width="1024" alt="CleanShot 2023-05-19 at 19 29 52@2x" src="https://github.com/zxch3n/tidy/assets/18425020/94fe37c3-07a1-46e6-92cf-5d3dc06125b7">
