### ISSUE TITLE
Thanks and a question about upstreaming

### ISSUE THREAD

**Issue by dhess** [zxch3n/tidy#5]
Hi, thank you for this wonderful library! We're creating a structure editor for ASTs for our pedagogical functional programming language, and have had a hard time finding a layout library that works well for ASTs. We recently discovered Tidy, and it looks very promising.

I have a question about submitting PRs. We've forked this repo in order to add Nix support, and in the process have cleaned up a few build- and packaging-related issues. We would like to upstream those changes, if you're interested. However, before we do that, I see that you're using npmmirror.com in the lockfile, rather than npmjs.org. Does npmmirror.com work better for you based on your location, or something like that? I ask because we've never heard of npmmirror.com and don't know anything about the organization/individuals who run it, and we're therefore uncomfortable using it for production. So for our own purposes, we're going to regenerate the `package-lock.json` file, which will complicate upstreaming.

Anyway, I'm not suggesting that you change anything on your end, just wondering whether you're committed to using npmmirror.com rather than npmjs.org. If so, we will just work around it if/when we upstream PRs.

Thanks again!

**Comment by zxch3n** [comment]
PRs are welcome! Yeah, npmmirror.com works better at my geo location. It's run by Alibaba. But I'm not committed to using it, you're free to change the lockfile to use npmjs.com instead.

**Comment by dhess** [comment]
Great, thanks! I'll close this now and submit an initial PR.
